In [49]:
import pandas as pd
import numpy as np

Free online book for data analysis using Python
https://wesmckinney.com/book/

#### Creating Pandas dataframe

In [52]:
data = {'col_1': [3, 2, 1, 0], 'col_2': ['a', 'b', 'c', 'd']}
df = pd.DataFrame.from_dict(data)

In [53]:
df

   col_1 col_2
0      3     a
1      2     b
2      1     c
3      0     d

In [54]:
# The number of cells
df.size

8

In [29]:
# Dimension
df.shape

(4, 2)

#### Retrieving data from data frame

In [55]:
df = pd.DataFrame([[1, 2], [4, 5], [7, 8]],
    index=['cobra', 'viper', 'sidewinder'],
    columns=['max_speed', 'shield'])

In [31]:
df.head()

            max_speed  shield
cobra               1       2
viper               4       5
sidewinder          7       8

In [32]:
df.loc["cobra", "shield"]

2

In [33]:
df.loc["viper"]

max_speed    4
shield       5
Name: viper, dtype: int64

#### Modifying values in data frame

In [34]:
df.loc['cobra'] = 10

In [35]:
df

            max_speed  shield
cobra              10      10
viper               4       5
sidewinder          7       8

In [36]:
df.loc[['viper', 'sidewinder'], ['shield']] = 50
df

            max_speed  shield
cobra              10      10
viper               4      50
sidewinder          7      50

In [37]:
# Modifying cell values based on conditions 
df.loc[(df['shield'] > 35) & (df["max_speed"] < 10)] = 0
df

            max_speed  shield
cobra              10      10
viper               0       0
sidewinder          0       0

#### Iterating through a data frame

In [16]:
# Iterate over DataFrame rows as (index, Series) pairs.
for idx, row in df.iterrows():
    print(idx)
    print(row)

cobra
max_speed    10
shield       10
Name: cobra, dtype: int64
viper
max_speed    0
shield       0
Name: viper, dtype: int64
sidewinder
max_speed    0
shield       0
Name: sidewinder, dtype: int64

#### Removing data from a data frame

In [17]:
df = pd.DataFrame([('falcon', 'bird', 389.0),
                    ('parrot', 'bird', 24.0),
                    ('lion', 'mammal', 80.5),
                    ('monkey', 'mammal', np.nan)],
                  columns=('name', 'class', 'max_speed'))
df

     name   class  max_speed
0  falcon    bird      389.0
1  parrot    bird       24.0
2    lion  mammal       80.5
3  monkey  mammal        NaN

In [18]:
df.pop('class')
df

     name  max_speed
0  falcon      389.0
1  parrot       24.0
2    lion       80.5
3  monkey        NaN

#### Generating descriptive statistics

In [38]:
df.describe()

       max_speed     shield
count   3.000000   3.000000
mean    3.333333   3.333333
std     5.773503   5.773503
min     0.000000   0.000000
25%     0.000000   0.000000
50%     0.000000   0.000000
75%     5.000000   5.000000
max    10.000000  10.000000

In [56]:
df = pd.DataFrame([('falcon', 'bird', 389.0),
                    ('parrot', 'bird', 24.0),
                    ('lion', 'mammal', 80.5),
                    ('monkey', 'mammal', np.nan)],
                  columns=('name', 'class_type', 'max_speed'))
df

     name class_type  max_speed
0  falcon       bird      389.0
1  parrot       bird       24.0
2    lion     mammal       80.5
3  monkey     mammal        NaN

In [46]:
pd.crosstab(df.name, df.class_type)

class_type  bird  mammal
name
falcon         1       0
lion           0       1
monkey         0       1
parrot         1       0