In [1]:
import pandas as pd
import numpy as np

Free online book for data analysis using Python
https://wesmckinney.com/book/

#### Creating Pandas dataframe

In [2]:
data = {'col_1': [3, 2, 1, 0], 'col_2': ['a', 'b', 'c', 'd']}
df = pd.DataFrame.from_dict(data)

In [3]:
df

   col_1 col_2
0      3     a
1      2     b
2      1     c
3      0     d

In [4]:
# The number of cells
df.size

8

In [5]:
# Dimension
df.shape

(4, 2)

#### Retrieving data from data frame

In [6]:
df = pd.DataFrame([[1, 2], [4, 5], [7, 8]],
    index=['cobra', 'viper', 'sidewinder'],
    columns=['max_speed', 'shield'])

In [7]:
df.head()

            max_speed  shield
cobra               1       2
viper               4       5
sidewinder          7       8

In [8]:
df.loc["cobra", "shield"]

np.int64(2)

In [9]:
df.loc["viper"]

max_speed    4
shield       5
Name: viper, dtype: int64

#### Modifying values in data frame

In [11]:
df.loc['cobra'] = 10 # change thw whole row

In [12]:
df

            max_speed  shield
cobra              10      10
viper               4       5
sidewinder          7       8

In [13]:
df.loc[['viper', 'sidewinder'], ['shield']] = 50 # change both rows for shield section
df

            max_speed  shield
cobra              10      10
viper               4      50
sidewinder          7      50

In [14]:
# Modifying cell values based on conditions 
df.loc[(df['shield'] > 35) & (df["max_speed"] < 10)] = 0
df

            max_speed  shield
cobra              10      10
viper               0       0
sidewinder          0       0

#### Iterating through a data frame

In [15]:
# Iterate over DataFrame rows as (index, Series) pairs.
for idx, row in df.iterrows():
    print(idx)
    print(row)

cobra
max_speed    10
shield       10
Name: cobra, dtype: int64
viper
max_speed    0
shield       0
Name: viper, dtype: int64
sidewinder
max_speed    0
shield       0
Name: sidewinder, dtype: int64

#### Removing data from a data frame

In [16]:
df = pd.DataFrame([('falcon', 'bird', 389.0),
                    ('parrot', 'bird', 24.0),
                    ('lion', 'mammal', 80.5),
                    ('monkey', 'mammal', np.nan)],
                  columns=('name', 'class', 'max_speed'))
df

     name   class  max_speed
0  falcon    bird      389.0
1  parrot    bird       24.0
2    lion  mammal       80.5
3  monkey  mammal        NaN

In [17]:
df.pop('class') # del or pop
df

     name  max_speed
0  falcon      389.0
1  parrot       24.0
2    lion       80.5
3  monkey        NaN

#### Generating descriptive statistics

In [18]:
df.describe()

        max_speed
count    3.000000
mean   164.500000
std    196.464373
min     24.000000
25%     52.250000
50%     80.500000
75%    234.750000
max    389.000000

In [19]:
df = pd.DataFrame([('falcon', 'bird', 389.0),
                    ('parrot', 'bird', 24.0),
                    ('lion', 'mammal', 80.5),
                    ('monkey', 'mammal', np.nan)],
                  columns=('name', 'class_type', 'max_speed'))
df

     name class_type  max_speed
0  falcon       bird      389.0
1  parrot       bird       24.0
2    lion     mammal       80.5
3  monkey     mammal        NaN

In [20]:
pd.crosstab(df.name, df.class_type)

class_type  bird  mammal
name
falcon         1       0
lion           0       1
monkey         0       1
parrot         1       0