In [20]:
import pandas as pd
import numpy as np

#### Series

A Series is a one-dimensional array-like object containing a sequence of values (of similar types to NumPy types) of the same type and an associated array of data labels, called its index. The simplest Series is formed from only an array of data:

In [21]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [22]:
# you can specify the index of the series yourself
obj2 = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [23]:
# accessing the index
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [24]:
# converting a pandas series to a Python dictionary
obj2.to_dict()

{'d': 4, 'b': 7, 'a': -5, 'c': 3}

#### Data frame

A DataFrame represents a rectangular table of data and contains an ordered, named collection of columns, each of which can be a different value type (numeric, string, Boolean, etc.). The DataFrame has both a row and column index; it can be thought of as a dictionary of Series all sharing the same index.

##### Creating a data frame

In [25]:
# From a dictionary 
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
# key = state, year, pop
frame = pd.DataFrame(data)
# didn't specify an index so starts at 0
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [26]:
frame.state.value_counts() # count for different values

state
Ohio      3
Nevada    3
Name: count, dtype: int64

In [27]:
frame.head(3) # specifing how many rows to print

  state  year  pop
0  Ohio  2000  1.5
1  Ohio  2001  1.7
2  Ohio  2002  3.6

In [28]:
frame.tail(3) # last rows to print

    state  year  pop
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [29]:
# Rows can also be retrieved by position or name with the special iloc and loc attribute
# Label-based indexing
# df.loc[row_label, column_label]
frame.loc[0]

state    Ohio
year     2000
pop       1.5
Name: 0, dtype: object

In [30]:
frame.loc[0, "year"]

np.int64(2000)

In [31]:
# Integer-based indexing
frame.iloc[1]

state    Ohio
year     2001
pop       1.7
Name: 1, dtype: object

In [32]:
# removing columns using del
del frame["pop"]

In [33]:
frame

    state  year
0    Ohio  2000
1    Ohio  2001
2    Ohio  2002
3  Nevada  2001
4  Nevada  2002
5  Nevada  2003

In [34]:
frame.columns

Index(['state', 'year'], dtype='object')

In [35]:
# You can conviniently convert the column names to a list
list(frame.columns)

['state', 'year']

In [36]:
# transposing a data frame: swapping the rows and columns
frame.T

          0     1     2       3       4       5
state  Ohio  Ohio  Ohio  Nevada  Nevada  Nevada
year   2000  2001  2002    2001    2002    2003

In [41]:
obj = pd.Series(np.arange(4.), index=["a", "b", "c", "d"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [42]:
obj["b"]

np.float64(1.0)

In [43]:
obj.iloc[1]

np.float64(1.0)

In [44]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [45]:
obj[["b", "a", "d"]]

b    1.0
a    0.0
d    3.0
dtype: float64

In [46]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [47]:
obj.loc[["b", "a", "d"]]

b    1.0
a    0.0
d    3.0
dtype: float64

#### Reading and writing files using Pandas

In [49]:
df = pd.read_csv("ex1.csv")
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'ex1.csv'

In [50]:
# reading in a file without a header
df2 = pd.read_csv("ex2.csv", header=None)
df2.head()

FileNotFoundError: [Errno 2] No such file or directory: 'ex2.csv'

In [123]:
# we can manually pass in a header for the data frame
pd.read_csv("ex2.csv", names=["a", "b", "c", "d", "message"])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [124]:
names = ["a", "b", "c", "d", "message"]
pd.read_csv("ex2.csv", names=names, index_col="message") # indexing using the message column

         a   b   c   d
message
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

In [125]:
df2.to_csv("df2.csv")

#### Handling missing data

In [126]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [54]:
# The isna method gives us a Boolean Series with True where values are null
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [127]:
# You can drop the NAs 
data = pd.Series([1, np.nan, 3.5, np.nan, 7])
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [56]:
data = data.dropna() # will delete rows with the missng values
data

0    1.0
2    3.5
4    7.0
dtype: float64

In [128]:
# same as 
data = data[data.notna()]
data

0    1.0
2    3.5
4    7.0
dtype: float64

In [129]:
df = pd.DataFrame(np.random.standard_normal((7, 3)))
df.iloc[:4, 1] = np.nan
df

          0         1         2
0 -1.285744       NaN  0.817303
1  0.319058       NaN -0.828427
2 -0.387612       NaN  0.573499
3  1.142504       NaN -0.316616
4  0.951941  0.899539  0.464085
5  0.837988  0.277375  0.444856
6  0.960052  1.031553  0.852791

In [59]:
# you can also fill in the missing values
df = df.fillna(0)
df

          0         1         2
0 -0.707290  0.000000  0.731904
1  0.775830  0.000000  0.403277
2 -0.057809  0.000000  0.316385
3  0.179403  0.000000 -1.386033
4  0.893055 -0.781747 -0.343307
5  1.447994 -0.402365 -1.381169
6 -0.114869  0.578260  0.455558

#### Removing duplicates

In [130]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"], "k2": [1, 1, 2, 3, 3, 4, 4]})
data

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [61]:
# The DataFrame method duplicated returns a Boolean Series indicating whether each row is a duplicate (its column values are exactly equal to those in an earlier row) or not:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [62]:
data = data.drop_duplicates()
data

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4